sudo:
  false

email:
  false

env:
  global:
    - USE_GITHUB_REPOSITORY=yes
    - secure: "fXoMQH7pTdaUpwWAuX7+KCZAyOnsVp9JaAeiVATOj3GuXOLtzMseShmqJQCkuVCqMtte8FlnBCGnaU/DyzWbUp11aSA6rsDji76aUKQS6dGIMUaABpyGLr9zNArTxRycYRvNIqsvpv25LTsX2zXrDHA6AUHzB72TOzKxOoKgtHRp29D9RTsyrlzh5ZnHVst63WFUjejgkykmmGJvM0pb28cE1LS11LlSbf7thBJCh80TmKVIJ3T6dBYEHVp0z6xNM5+707uNEp1ITJ1I6dIxDyPLDBtppevv7bJAk8aIPVgdrEctut+kqlsIMCQSjnQlk2h1nuLNDDoBadmX0vkeXP4BgAVU2YaA8WBx9Uv6AghpIV9RSV6O7gmkSHmviKpUhroPzykHBagISiFFYaD85eNTYJxcnbwrEqThf1CRTQ21bGD9qmBQPVrgkarkwqx+HcYEBaOJjAYrATpVz9QHKtSdm7Z/N3ubchoXqGtB1uSTiE1520W2MwQ0pZEd6qqGQPOlncjya3XbN/kbwSVXLDBLT8rOifF+SBtMqR3V79W1VzvjoTcGVjwcylmrAmBDlf8RWJm+lvDURLsfzHO3qlK1TZmswGCUAP/tUFFHJR4EyuwFE1wYLCaGRhs4CmRnltc0wICY6A1jb3RrFGQnJ7l6rSRuA6ECJd6zH2MWWF0="

language:
  ruby

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1

cache: bundler

before_install:
  - gem install bundler

script:
  - bundle exec rake coverage
