email:
  false

dist:
  trusty

git:
  depth:
    false

env:
  global:
    - secure: "UMNZRxH8VMz35I1qGyzYAfZU6aVH8A204/521jzBrlOAwg1ee8yrXrGy/D2h0gFwkX33edp/pmt2f005YeI0pCFitYWqUI0qVPUA9wdM4PhtlNZZNpl1ep5hthu5Ay0juMujhEEMaAgt2Mi5JGC9Y4mhOciU8KTEsTfyul7rktkcjARe+605e7WiS5DIJIB1UA4TSOW6Qv4m0aDsY07NOVfJCmqtDOrckmld3PDfQHMOXCS0CbK/HujecjAYNUtn6fhpl8XzdVIqB2GmUaKYa2+2xZl4QZM8xDCl6fkwn42vPokS9v2FPzNkHcs/7tRCIzyqXr+KrWG+G+4J+tmWiys20EnPKDeHQRPUg9DbUtvmSXG+6zoib3/whOrapWMBjHpSl+gu5WSBzMzZYUjaru+Pw+EVsIU7w4qFTE72lmQdrfCy7yaq4Pfy5eQZocdaP7pK0RzJuZOqS6xdJm1ptpUGpbUUqlh0uqqWbKwjRPoxGw4MVki4kAYn0dPAhO/KUAdckOHtRL2tW4FxiAcSuOWWtFdkF+wfIMn/OKg29K1+t6/UZYcn2CBgUao55/9mbKydG35dX54paqcEYG23n7mbrdIHUgGJZeKIuXq9yI4z+0n7AEGAZnFn8veEiUozav5IziifZfoGjhcx+1Z5IEoeLS5x0dgCFKYc66Z/oLk="

language:
  ruby

cache:
  bundler

matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.9
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes
    - rvm: 2.5.7
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes
    - rvm: 2.6.5
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes
    - rvm: 2.7.0
      env: RUBYOPT=--enable-frozen-string-literal USE_FIXED_GEMS=yes

addons:
  sonarcloud:
    organization:
      rggen
    token:
      secure: "LC71NgdKuMlDo1KM1ejjiAXCDb0OiKZHuKUbSLFK2svIyqcrwAiugAUlYGxKGfhY3oyv8DCQy3xc6Ybx00qf2J0g3mhER+JgkBulYQj63Gb/nmFi8zE4kTio4kBlq1m72bshySqphwTTakjRoe+oRw0XrB1WtjuRRV5+RWQEgoBblXieNeVUFydNk+SKnXkXZRXKW31+VyZYW/ONeA316WtBx7Tw+Y8GaPzq4IClr/xlOepVCCZwxBvj5QIkZkSAVwdzCcKB6aA92AK+0jUxbcUz+li/bSKhGnElcHdv3bfgda0eT9RTNWqBJqslSSkT6z855ckJwn2q2KOwvQrqfYKQrXicIV0Qua+SHZh3vxtKchrLh0E/bN5Bt+T0fCY0HA4NE6KeY1x6X8rCJhYn5S7/b2Va1qiSshnICuUgm10wC2Jwa9JMTiNU9DrrEJwiOjhEgmtjOoez7JQJn0xIKLN+nuTBqsvLzcvAllGGJymjDra974LV0pncSRexxCP6Kx4xhx0gJ4Ffgra+IViGSix9v3QvU3PqxRoXytlJglo/4S86bHhLBgujUhjY49azeujuCYK6JmnubIf1SE5P0D+oXjub2WJDNjUu5KhKmQxRC4ttFrdvQadYRg19m2mn7Klep6/y+qMRBvJlMtk+WrsVqYZ3rGV1/9g1NbwXvI4="

before_install:
  - "env -u RUBYOPT gem update --system"
  - "env -u RUBYOPT gem install bundler"

script:
  - bundle exec rake coverage
  - sonar-scanner
